main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from notes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
]

main/notes/urls.py
from django.urls import path
from . import views
app_name = 'notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

main/notes/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

main/notes/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': 'Title',
            'content': 'Text',
        }

main/notes/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from .models import Question
from .forms import QuestionForm
# Create your views here.

def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list':question_list}
    return render(request, 'notes/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'notes/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('notes:detail', question_id=question.id)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('notes:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'notes/question_form.html', context)

main/templates/base.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-BOVP5XmATw1 +K9KRQjQERJvTumQWOnPEZVF6L/Z6nronJ3oUOFUFpCjEUQoug2+1" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/4.6.0/jquery.min.js"></script>
    <title>Welcome</title>
</head>
<body>
{% include "navbar.html" %}

{% block content %}
{% endblock %}
</body>
</html>

main/templates/navbar.html
<!--네비게이션바 -->
<nav class="navbar navbar-expand-1g navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'notes:index' %}">Notes</a>
    <button class="navbar-toggler mI-auto" type= "button" data-toggle="collapse" data-target= "#navbarNaV"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class= "navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-@" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="#">login</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/notes/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<h1>{{ question.subject }}</h1>

<div>
    {{ question.content }}
</div>
<br>
<h5>{{ question.answer_set.count}} numbers of answer is commented.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
        {% endfor %}
    </ul>
</div>
<br>
<form action="{% url 'notes:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="answer_created">
</form>

main/templates/notes/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Ask Question</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

main/templates/notes/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="table-container">
    <table class="table">
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'notes:detail' question.id %}">{{ question.subject }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No more question.</p>
{% endif %}
        <a href="{% url 'notes:question_create' %}" class="btn btn-primary">Ask Question</a>
        </table>
</div>
{% endblock %}